rooms:
  name: test
  hotelList:
    - hotel: 明德楼
      rooms: 104标准教室
        104标准教室（2）
        105标准教室
        105标准教室（2）
        308标准教室
        309标准教室
        505标准教室
        505标准教室（2）
        506标准教室
        506标准教室（2）
        507标准教室
        507标准教室（2）
        508标准教室
        508标准教室（2）
        504标准教室
        504标准教室（2）
        504标准教室（3）
        106标准教室
        106标准教室（2）
        107标准教室
        107标准教室（2）
        206标准教室
        206标准教室（2）
        207标准教室
        207标准教室（2）
        208标准教室
        208标准教室（2）
        209标准教室
        209标准教室（2）
        308标准教室（2）
        309标准教室（2）
        310标准教室
        310标准教室（2）
        311标准教室
        311标准教室（2）
        408标准教室（2）
        409标准教室(2)
        410标准教室
        410标准教室（2）
        411标准教室
        411标准教室（2）
      datasource: yuyan
    - hotel: 致远楼
      rooms: 104标准教室
        104标准教室（2）
        105标准教室
        105标准教室（2）
        106标准教室
        106标准教室（2）
        107标准教室
        107标准教室（2）
        205标准教室
        205标准教室（2）
        206标准教室
        206标准教室（2）
        207标准教室
        207标准教室（2）
        208标准教室
        208标准教室（2）
        209标准教室
        209标准教室（2）
        307标准教室
        307标准教室（2）
        308标准教室
        308标准教室（2）
        309标准教室
        309标准教室（2）
        310标准教室
        310标准教室（2）
        407标准教室
        407标准教室（2）
        408标准教室
        408标准教室（2）
        409标准教室
        409标准教室（2）
        410标准教室
        410标准教室（2）
        505标准教室
        505标准教室（2）
        506标准教室
        506标准教室（2）
        507标准教室
        507标准教室（2）
        508标准教室
        508标准教室（2）
      datasource: yuyan
    - hotel: 弘毅楼
      rooms: 103标准教室
        103标准教室（2）
        104标准教室
        104标准教室（2）
        105标准教室
        105标准教室（2）
        106标准教室
        106标准教室（2）
        107标准教室
        107标准教室（2）
        205标准教室
        205标准教室（2）
        206标准教室
        206标准教室（2）
        207标准教室
        207标准教室（2）
        208标准教室
        208标准教室（2）
        307标准教室
        307标准教室（2）
        308标准教室
        308标准教室（2）
        309标准教室
        309标准教室（2）
        310标准教室
        310标准教室(2)
        408标准教室
        408标准教室（2）
        409标准教室
        409标准教室（2）
        410标准教室
        410标准教室（2）
        411标准教室
        411标准教室（2）
        505标准教室
        505标准教室（2）
        506标准教室
        506标准教室（2）
        507标准教室
        507标准教室（2）
        508标准教室
        508标准教室（2）
      datasource: yuyan
    - hotel: 尚静楼
      rooms: 209
      datasource: yuyan
    - hotel: 三灶中心幼儿园
      rooms: 小一班
               小二班
               小三班
               小四班
               小五班
      datasource: pub
