myapp:
  name: "shiro"
  job:
    toSend:
      - huihuixiao@pihyun.com
      - liangzhuwu@pihyun.com
database:
  host: 125.216.38.66
  port: 63634
  databasename: nx_web
  username: root
  password: NxLocalDb20Se

mysqlSize:
  max: 8
  min: 2
  size: 2